fast_nwes_src/fast_news_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls"), name="home-urls"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fast_nwes_src/home/urls.py
from django.urls import path

from .views import *

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home-view"),
    path("about", AboutView.as_view(), name="about-view"),
]

fast_nwes_src/home/models.py
from django.db import models

# Create your models here.

fast_nwes_src/home/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = "home/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home Page"
        return context


class AboutView(TemplateView):
    template_name = "home/about.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["title"] = "About Page"
        return context


# Function based view
# def home(request):
#     return render(request, "home/home.html", {'title': "Home page"})

# def about(request):
#     return render(request, "home/about.html")

fast_nwes_src/templates/home/about.html
{% extends "home/master.html" %}


{% block title %}
    About us
{% endblock title %}
    


{% block content %}
<h4>
    About Page
</h4>
{% endblock content %}

fast_nwes_src/templates/home/home.html
{% extends "home/master.html" %}


{% block title %}
    {{ title }}
{% endblock title %}
    


{% block content %}
<h4>
    Home Page
</h4>
{% endblock content %}

fast_nwes_src/templates/home/inc/header.html
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'home:home-view' %}" class="nav-link px-2 link-secondary">Home</a></li>
                <li><a href="{% url 'home:about-view' %}" class="nav-link px-2 link-dark">About</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Contact us</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo" class="rounded-circle" width="32" height="32">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

fast_nwes_src/templates/home/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

        {% block title %}
        Fast News Blog
        {% endblock title %}

    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
</head>

<body>
    {% include 'home/inc/header.html' %}
    <main class="container">

        {% block content %}

        {% endblock content %}

    </main>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>